id: P902D4234
initial_creation_type: input
source_metadata:
  title: Trulshik Rinpoche Series
  language: pt
  description: Texts by and about Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö ('khrul
    zhig ngag dbang chos kyi blo gros, 1924–2011), one of the teachers of His Holiness
    the Fourteenth Dalai Lama.
  volume:
    4a63150a9f40446dad953588330f83ac:
      title: Advice for Retreat
      parent: Advice
    acf1a944b5a149dd8723e4c570e526c8:
      title: Advice for Tenzin Jamchen
      parent: Advice
    8885e99feb24497e8370bcf09fe5f9cc:
      title: Advice in Four Lines
      parent: Advice
    5f768262a0714bc887457bab54593f60:
      title: A Prayer for Translators
      parent: Aspiration Prayers
    6f21c122705f44f494dc55b6d6bd8916:
      title: A Prayer for the Spread of Kyabje Dilgo Khyentse Rinpoche’s Termas
      parent: Aspiration Prayers
    7acb1a035b0f4bc79888851b71630342:
      title: Prayer of the View, Meditation and Conduct
      parent: Aspiration Prayers
    4085f4a0f60245649141455f2129814c:
      title: Profound Prayer of Aspiration
      parent: Aspiration Prayers
    cb6af5dd68ee42eea67361540be0bf86:
      title: 'The Quintessential Blessing: A Guru Yoga'
      parent: Guru Yoga
    f9395d98400d46caab5df97c36afc67f:
      title: 'Granting the Wish for Immortality: A Prayer for the Long Life of Dzarong
        Trulshik Rinpoche, the Representative of Guru Rinpoche'
      parent: Long Life Prayers
    ca4e70eb57304319a3bc82396926133a:
      title: Long Life Prayer for Alak Zenkar Rinpoche
      parent: Long Life Prayers
    fa7cb21c6bf548acbf6de32f52e09e9d:
      title: Long Life Prayer for Kyabje Dzarong Trulshik Rinpoche
      parent: Long Life Prayers
    eb9dd14c4b0e46de87e38e27ae107189:
      title: Long Life Prayer for Lodi Gyari Rinpoche
      parent: Long Life Prayers
    cd61783610ef4004a5a9e9561717ba57:
      title: Long Life Prayer for Mayum Tsering Wangmo
      parent: Long Life Prayers
    1c7e8c88f48e48be8805145a10f04b44:
      title: Prayer for the Long Life of Chökyi Nyima Rinpoche
      parent: Long Life Prayers
    1899ebdb132043d7b1d55907edd7e3e9:
      title: Prayer for the Long Life of Dilgo Khyentsé II of Shechen, Urgyen Tenzin
        Jigme Lhundrup
      parent: Long Life Prayers
    d57b68c2e92b4a1b950fe673dd71c9df:
      title: Prayer for the Long Life of His Holiness the Fourteenth Dalai Lama
      parent: Long Life Prayers
    5843fcfecb3a45ff8f546bc1cb1192a4:
      title: Prayer for the Long Life of Sogyal Rinpoche—chimé kunnyé
      parent: Long Life Prayers
    8573428d0f6d465eb3a88787b439357e:
      title: Prayer for the Long Life of Sogyal Rinpoche—sönam jewé
      parent: Long Life Prayers
    77e6a29c54e44a359befc22f81026b70:
      title: Prayer for the Long Life of Taklung Tsetrul Rinpoche
      parent: Long Life Prayers
    5cbd85dd7e9b4fbdbb20231582c93259:
      title: The Attainment of Immortality
      parent: Long Life Prayers
    78e6cea345084718ba13445d4f5f6b33:
      title: A Homage to His Holiness the Dalai Lama
      parent: Praise
    846c40803797461b8614f0644bb8443c:
      title: Verses of Homage
      parent: Praise
    34d2b0a94dfa4fdc80d26cc6f00f35dd:
      title: Verses of Homage to the Buddhas and Bodhisattvas Together with their
        Mantras
      parent: Praise
    ccf17b12f3604b6e85ee5d3b7f3f5488:
      title: A Record of the Successive Incarnations
      parent: Prayers
    65c833f3700b4e439ef1423fd6f6e86a:
      title: 'Gateway for the Faithful: A Supplication Recalling the Lives and Liberation
        of Kyabje Trulshik Rinpoche, Ngawang Chökyi Lodrö'
      parent: Prayers
    59eef1db16c94e88940651f85c0aa5e9:
      title: A Brief Daily Practice of Damdrip Nyepa Kunsel
      parent: Sādhanas
    a1ca218b58994c2185fd11a2e50babdc:
      title: Prayer for the Swift Rebirth of Kyabjé Trulshik Rinpoche
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T01:52:59.295925'
last_modified_at: '2022-03-01T01:52:59.295928'
